server:
  port: 8099
  servlet:
    context-path: /
  tomcat:
    uri-encoding: utf-8
    #最大线程数，默认200
    max-threads: 800
    min-spare-threads: 30
    max-http-form-post-size: 20MB



mybatis:
  type-aliases-package: com.example.demo.domain
  mapperLocations: classpath:mybatis/*Mapper.xml
  configLocation: classpath:mybatis/mybatis-config.xml
spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  http:
    log-request-details: true
  datasource:
    url: jdbc:mysql://localhost:3306/chat?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
debug: true
logging:
  level:
    com.example.controller: DEBUG
    com.example.config: DEBUG
  file:
    path: /usr/local/log/spring.log
